name: Ejecucion del Bot de Ventas
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Subimos a la 3.10 para evitar errores de vejez

      - name: Instalar herramientas
        run: |
          python -m pip install --upgrade pip
          pip install -U google-generativeai

      - name: Ejecutar el Bot de Analisis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python bot.py
