name: Ejecutar Bot Amazon

on:
  workflow_dispatch:      # Permite el bot√≥n manual "Run workflow"
  schedule:
    - cron: '0 14 * * *'  # Ejecuta autom√°tico a las 9:00 AM EST (aprox)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar c√≥digo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: üõ†Ô∏è Instalar Herramientas (La parte clave)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: üöÄ Correr el Robot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
