name: Ejecucion Automatica del Bot con Video
on:
  workflow_dispatch: # Botón manual
  schedule:
    - cron: '0 8 * * *' # 8:00 AM UTC todos los días

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias del Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick
          # Configurar ImageMagick para que permita procesar textos (seguridad de Linux)
          sudo sed -i 's/domain="path" rights="none" pattern="@\*"/domain="path" rights="read|write" pattern="@\*"/g' /etc/ImageMagick-6/policy.xml

      - name: Instalar Librerias de Python
        run: |
          pip install requests gspread google-auth moviepy gTTS

      - name: Ejecutar el Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python bot.py

      - name: Guardar Video como Resultado
        uses: actions/upload-artifact@v4
        with:
          name: videos-generados
          path: "*.mp4"
          retention-days: 5
