name: Ejecucion Automatica del Bot
on:
  workflow_dispatch: # Permite que lo sigas ejecutando a mano si quieres
  schedule:
    # Este es el "reloj". El formato es: Minuto Hora Dia Mes Dia_de_la_semana
    # 0 8 * * * significa: Todos los d√≠as a las 08:00 AM UTC
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: pip install requests

      - name: Ejecutar el Bot de Analisis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python bot.py
