name: CHM Brand USA Bot

on:
  schedule:
    - cron: '0 13 * * *' # Corre una vez al día
  workflow_dispatch: # Botón manual para probar AHORA

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar librerías
        run: pip install requests beautifulsoup4
      - name: Ejecutar Bot
        env:
          # Inyectamos tus llaves reales en el código
          SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
