name: Ejecucion Automatica del Bot con Video
on:
  workflow_dispatch: # Botón manual para pruebas
  schedule:
    - cron: '0 8 * * *' # Se ejecuta a las 8:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependencias del Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick
          # ESTA LÍNEA REPARA EL ERROR DE PERMISOS DE IMAGEMAGICK EN GITHUB ACTIONS
          sudo sed -i 's/domain="path" rights="none" pattern="@\*"/domain="path" rights="read|write" pattern="@\*"/g' /etc/ImageMagick-6/policy.xml

      - name: Instalar Librerias de Python
        run: |
          pip install requests gspread google-auth moviepy==1.0.3 gTTS

      - name: Ejecutar el Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python bot.py

      - name: Guardar Video Generado
        uses: actions/upload-artifact@v4
        with:
          name: video-resultado
          path: "*.mp4"
          retention-days: 3
